### ISSUE TITLE
特意用蜗牛大佬的文章试了下。。。

### ISSUE THREAD

**Issue by g0fcn** [Moraxyc/ai-summary-hugo#43]
Traceback (most recent call last):
  File "/home/runner/work/eallion.com/eallion.com/ai-summary-hugo/requestSummary.py", line 18, in generate_summary
文章已生成总结: Hugo .GitInfo 的替代方案
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 
You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 
Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/eallion.com/eallion.com/ai-summary-hugo/main.py", line 61, in <module>
    main()
  File "/home/runner/work/eallion.com/eallion.com/ai-summary-hugo/main.py", line 37, in main
    summary_content = generate_summary(post.content)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/eallion.com/eallion.com/ai-summary-hugo/requestSummary.py", line 26, in generate_summary
    except openai.error.OpenAIError as e:
           ^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'error'这是咋回事

**Comment by Moraxyc** [comment]
请参照文档更新运行方式

**Comment by xinkeji** [comment]
![Screenshot_2024-03-04-21-05-00-516_com.android.browser.jpg](https://github.com/Moraxyc/ai-summary-hugo/assets/33138729/ce0fcb97-c882-4905-b9d4-2483d373dd7a)

大佬我睡不着觉😫，新增文章也要10几分钟，
